# preload = ~/Pictures/wallpapers/Ranni.jpg
# wallpaper = ,~/Pictures/wallpapers/Ranni.jpg

# splash = false

wallpaper {
  monitor = eDP-1
  path = ~/Pictures/wallpapers/Ranni.jpg
  fit_mode = cover
}