context.modules = [
  {   name = libpipewire-module-echo-cancel
      args = {
          aec.method = webrtc
          aec.args = {
              noise_suppression = true
              echo_cancel = true
              extended_filter = true
              delay_agnostic = true
          }
          capture.props = {
              node.name = "echo-cancel-capture"
          }
          playback.props = {
              node.name = "echo-cancel-playback"
          }
      }
  }
]
