#############
### Fonts ###
#############
font_family FreeMono





#####################
### Terminal Bell ###
#####################
enable_audio_bell no





#####################
### Window Layout ###
#####################
window_padding_width 2 4





###############
### Tab Bar ###
###############
# Powerline-style Tab Bar
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style angled
tab_bar_align left
tab_bar_min_tabs 1

# Standard margins
# tab_bar_margin_width 4.0
# tab_bar_margin_height 2.0 0.0

# High contrast colors
active_tab_foreground #ffffff
active_tab_background #7589aa
active_tab_font_style bold
inactive_tab_foreground #e0e0e0
inactive_tab_background #555555
inactive_tab_font_style normal

# Slightly darker tab bar background
tab_bar_background #2d2d2d

# Include index and title
tab_title_template "{index}: {title}"
active_tab_title_template "{index}: {title}"

# Show activity
tab_activity_symbol "●"





####################
### Color Scheme ###
####################
background_opacity 0.9
background_blur 0





########################
### Mappable Actions ###
########################
map ctrl+shift+} next_window
map ctrl+shift+{ previous_window
map ctrl+backspace send_text all \x17